# Test
name: Reusable workflow test
on:
  workflow_call:
    inputs:
      msg:
        description: input message to print
        required: true
        type: string

jobs:
  org-specific-workflow:
    name: job only allows this workflow to be called by repos of the same owner
    runs-on: ubuntu-latest
    steps:
      - name: test
        if: ${{ github.repository_owner == lamelameo }}
        run: echo hi lameo
      - name: reject
        if: ${{ github.repository_owner != lamelameo }}
        run: exit 1
  job1:
    name: prints input message, with name of org and repo of caller workflow
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo ${{ inputs.msg }}
      - name: get org/repo 
        run: echo "org - ${{ github.repository }}, repo - ${{ github.repository_owner }}"
